the-julge-part3-6team/the-julge-part3-6team

- src/pages/dev-preview/index.tsx
- src/shared/components/Button/CustomButton/CustomButton.tsx
- src/shared/components/Button/GrayButton/GrayButton.tsx
- src/shared/components/Button/RedButton/RedButton.tsx
- src/shared/components/Modal/Modal.tsx
- src/shared/components/Toast/Toast.tsx
- src/shared/store/useModal.ts
- src/shared/store/useToast.ts
fix: Toast & Modal 사용법 변경
Toast와 Modal을 여는 onClick event 동작 시 key를 추가
> fix: Toast & Modal 사용법 변경

- src/shared/components/Table/Badge/Badge.tsx
- src/shared/components/Table/Table.tsx
rename: Styled js파일 네이밍 변경
@/shared/components/table/bedge.styled.ts
--> @/shared/components/table/Bedge.styled.ts
@/shared/components/table/table.styled.ts
--> @/shared/components/table/Table.styled.ts
> rename: Styled js파일 네이밍 변경

- src/pages/dev-preview/index.tsx
- src/shared/components/Table/Table.tsx
- src/types/table.ts
> type: 기존 테이블 타입 분리 처리

- src/pages/mypage/index.styled.ts
- src/pages/mypage/index.tsx
- src/widgets/mypage/index.ts
- src/widgets/mypage/ul/addProfile/AddProfile.styled.ts
- src/widgets/mypage/ul/addProfile/AddProfile.tsx
> add: MyPage 추가

- src/pages/mypage/index.tsx
- src/shared/components/Footer/Footer.styled.ts
> style: footer 스타일 수정, 미사용 코드 삭제

- src/pages/mystore/index.tsx
> github template 테스트를 위한 merge

- src/pages/mypage/edit/index.styled.ts
- src/pages/mypage/edit/index.tsx
- src/pages/mypage/index.tsx
- src/types/myPage.ts
- src/widgets/mypage/model/useUserUpdateForm.ts
- src/widgets/mypage/ui/ViewProfile/ViewProfile.styled.ts
- src/widgets/mypage/ui/ViewProfile/ViewProfile.tsx
- src/widgets/registrationMyPage/ui/editProfileModal/EditProfileModal.tsx
> feat: myPage > Edit

- src/pages/mystore/index.tsx
> fix: mystore 등록한 가게 없을 시 공고 등록 widgets 안 보이게 하기

- src/components/notice/model/handleValidate.ts
- src/components/notice/model/noticeSubmit.ts
- src/pages/notice/create/index.styled.ts
- src/pages/notice/create/index.tsx
- src/widgets/createNotice/ui/inputContent/InputContainer.tsx
> feat: 공고 등록 validation 기능 구현

- package-lock.json
- package.json
- src/types/myPage.ts
- src/widgets/mypage/model/useUserUpdateForm.ts
- src/widgets/registrationMyPage/ui/registrationProfile/RegistrationProfile.tsx
> mypage > create /// zod를 이용해서 유효성 검사 추가 했습니다.
> useUserUpdateForm.ts 파일에서 useMutation 안에서 밸리데이션을 넣는게 맞는지
좀 더 나눌 수 있는지가 궁금합니다.
> feat: mypage > create /// 유효성검사 추가

- src/widgets/mypage/model/useUserUpdateForm.ts
- src/widgets/mypage/model/useUserValidateion.ts
- src/widgets/registrationMyPage/model/isValidDate.ts
- src/widgets/registrationMyPage/ui/registrationProfile/RegistrationProfile.tsx
> zod와 react-query 기능 분리 했습니다.
> feat: mypage > create /// zod와 react-query 기능 분리

- src/constant/user.ts
- src/models/user/isValidDate.ts
- src/models/user/useUserUpdateForm.ts
- src/pages/mypage/edit/index.tsx
- src/widgets/registrationMyPage/ui/registrationProfile/RegistrationProfile.tsx
> refactor: mypage /// 리팩토링

- src/models/user/isValidDate.ts
- src/shared/types/user.ts
- src/widgets/registrationMyPage/ui/registrationProfile/RegistrationProfile.tsx
> 타입 명시를 좀 더 명확하게 해서 알아보기 쉽게 했습니다.
> refactor: 타입 리팩토링

- src/shared/components/Header/Header.tsx
- src/shared/components/Header/employee/Employee.tsx
- src/shared/components/Header/employer/Employer.tsx
- src/shared/utils/axios.ts
> fix: cookie remove fixed

- src/shared/components/Header/employee/Employee.tsx
> fix: logout cookie fixed

- src/pages/mypage/index.tsx
- src/shared/utils/renderSpinner.tsx
> feat: renderSpinner 함수 추가

- src/pages/mystore/index.tsx
- src/shared/utils/renderSpinner.tsx
> fix: renderSpinner 함수수정

- src/models/alert/useGetAlerts.ts
- src/models/auth/useSigninMutation.ts
- src/shared/components/Header/employee/Employee.tsx
- src/shared/components/Header/employer/Employer.tsx
- src/shared/utils/axios.ts
fix: login & logout cookie 관련 기능 수정
> fix: login & logout cookie 관련 기능 수정

- src/models/alert/useGetAlerts.ts
- src/models/notice/useGetNotice.ts
- src/pages/_app.tsx
- src/pages/mystore/index.tsx
> feat: react-query provider 설정

- src/shared/utils/replacePhoneValue.ts
- src/widgets/mypage/ui/ViewProfile/ViewProfile.tsx
- src/widgets/registrationMyPage/ui/registrationProfile/RegistrationProfile.tsx
> 핸드폰 번호를 입력하면서 view와 input value 입력시 - 추가했습니다.
- 함수를 import해서 사용만 하시면 됩니다.
> feat: 핸드폰 번호 ( - ) 추가

- src/pages/mystore/create/index.tsx
- src/widgets/createStore/index.ts
- src/widgets/createStore/ui/inputContent/InputContent.tsx
- src/widgets/createStore/ui/modalContainer/ModalContainer.styled.ts
- src/widgets/createStore/ui/modalContainer/ModalContainer.tsx
- src/widgets/mystore/ui/StoreContent/StoreContent.styled.ts
refactor: pages > mystore > create > index.tsx 리펙토링
> refactor: pages > mystore > create > index.tsx 리펙토링

- src/models/store/mutateUpdateStore.ts
- src/models/store/usePatchFromData.ts
- src/pages/mystore/create/index.tsx
- src/pages/mystore/edit/index.tsx
- src/widgets/createStore/ui/inputContent/InputContent.styled.ts
- src/widgets/createStore/ui/inputContent/InputContent.tsx
- src/widgets/updateStore/index.ts
- src/widgets/updateStore/ui/ModalContainer/ModalContainer.styled.ts
- src/widgets/updateStore/ui/ModalContainer/ModalContainer.tsx
refactor: pages > mystore > edit 리펙토링
> refactor: pages > mystore > edit 리펙토링

- src/models/user/useUserSupportList.ts
- src/pages/mypage/index.tsx
- src/widgets/mypage/ui/ApplicationContent/ApplicationContent.tsx
> 프로필, 신청내역 분기 처리 및 유저의 지원 목록 조회 추가 했습니다.
> feat: 프로필, 신청내역 분기 처리 및 유저의 지원 목록 조회 추가

- src/pages/mystore/create/index.tsx
- src/pages/notice/create/index.tsx
- src/widgets/createNotice/index.ts
- src/widgets/createNotice/ui/Modalcontainer/ModalContainer.styled.ts
- src/widgets/createNotice/ui/Modalcontainer/ModalContainer.tsx
- src/widgets/createNotice/ui/inputContent/InputContainer.tsx
- src/widgets/createNotice/ui/inputContent/InputContent.styled.ts
> refactor: 공고등록 페이지 리펙토링

- src/models/notice/useGetNotices.ts
- src/pages/noticelist/index.tsx
- src/pages/noticelist/useGetNotices.ts
- src/shared/components/Post/PostCard/PostCard.tsx
- src/shared/components/Post/PostList/PostList.tsx
- src/shared/types/filterState.ts
> Feat: noticelist 페이지 수정 중

- src/shared/components/Header/Header.styled.ts
> style: 해더 반응형 스타일 수정

- src/components/notice/ui/noticeCardList/NoticeCardList.styled.ts
- src/components/notice/ui/noticeCardList/NoticeCardList.tsx
- src/components/user/ui/AddProfile/AddProfile.styled.ts
- src/models/auth/logout.ts
- src/models/auth/useSigninMutation.ts
- src/models/employer/useSaveImage.ts
- src/models/notice/useGetNoticeByStoreId.ts
- src/models/notice/useUpdateNoticeList.ts
- src/models/user/useUserUpdateForm.ts
- src/shared/components/Header/employee/Employee.tsx
- src/shared/components/Header/employer/Employer.tsx
- src/shared/utils/observerByScroll.ts
- src/shared/utils/useRouterGuard.ts
- src/widgets/mystore/ui/NoticeContent/NoticeContent.tsx
> feat: mystore 페이지 무한스크롤 구현

- src/components/user/index.ts
- src/components/user/ui/ApplicationHistoryTableContent/ApplicationHistoryTableContent.styled.ts
- src/components/user/ui/ApplicationHistoryTableContent/ApplicationHistoryTableContent.tsx
- src/pages/mypage/index.tsx
- src/shared/components/Table/Badge/Badge.tsx
- src/shared/components/Table/Badge/badge.styled.ts
- src/shared/components/Table/Table.tsx
- src/shared/types/table.ts
- src/shared/utils/formatNumberWithCommas.ts
- src/widgets/mypage/ui/ApplicationContent/ApplicationContent.tsx
> 마이 페이지에 공고가 있을경우 테이블 추가 했습니다.
> feat: mypage > 테이블 추가

- package-lock.json
- package.json
> feat: swiper 라이브러리 추가

- src/components/filter/ui/Filter.styled.ts
- src/models/notice/useGetNotices.ts
- src/pages/noticelist/index.tsx
- src/shared/components/Post/PostCard/PostCard.styled.ts
- src/shared/store/useFilterStore.ts
- src/shared/types/filterState.ts
- src/shared/utils/dateTransform.ts
> noticelist api 수정중

- src/components/user/ui/ApplicationHistoryTableContent/ApplicationHistoryTableContent.styled.ts
- src/components/user/ui/ApplicationHistoryTableContent/ApplicationHistoryTableContent.tsx
> style: 스타일 수정

- src/components/notice/ui/noticeCardList/NoticeCardList.styled.ts
- src/components/store/ui/storeCard/StoreCard.styled.ts
- src/pages/mystore/index.styled.ts
- src/shared/components/Post/PostCard/PostCard.styled.ts
- src/shared/components/Post/PostInform/PostInform.styled.ts
- src/shared/components/Post/PostPrice/PostPriceBadge.styled.ts
> style: store > card 스타일 수정

- src/models/notice/useGetNotice.ts
- src/models/notice/useGetNoticeList.ts
- src/models/notice/usePatchNotice.ts
- src/pages/notice/edit/index.styled.ts
- src/pages/notice/edit/index.tsx
- src/shared/utils/useRouterGuard.ts
- src/widgets/createNotice/ui/inputContent/InputContainer.tsx
- src/widgets/updateNotice/ui/modalContainer/ModalContainer.styled.ts
- src/widgets/updateNotice/ui/modalContainer/ModalContainer.tsx
> feat: notice edit 페이지 구현

- src/shared/utils/axios.ts
- src/widgets/createNotice/ui/inputContent/InputContainer.tsx
feat: 401일 경우 axios interceptor 추가
> feat: 401일 경우 axios interceptor 추가

- src/pages/noticedetail/index.styled.ts
- src/shared/components/Post/PostInform/PostInform.styled.ts
- src/shared/components/Post/PostPrice/PostPrice.styled.ts
> style: noticeDetail 스타일 수정

- src/components/user/ui/ApplicationHistoryTableContent/ApplicationHistoryTableContent.styled.ts
- src/components/user/ui/ApplicationHistoryTableContent/ApplicationHistoryTableContent.tsx
- src/models/user/useUserSupportList.ts
- src/shared/components/Table/Table.tsx
- src/shared/components/Table/table.styled.ts
- src/shared/types/table.ts
- src/widgets/mypage/ui/ApplicationContent/ApplicationContent.tsx
> mypage > 테이블 페이지 네이션 추가

- src/models/employer/useGetApplicantsForJobPosting.ts
- src/pages/noticedetailceo.tsx
- src/shared/components/OwnerTable/Badge/Badge.styled.ts
- src/shared/components/OwnerTable/Badge/Badge.tsx
- src/shared/components/OwnerTable/OwnerTable.styled.ts
- src/shared/components/OwnerTable/OwnerTable.tsx
- src/shared/components/OwnerTable/TableBtn/TableBtn.styled.ts
- src/shared/components/OwnerTable/TableBtn/TableBtn.tsx
> noticedetail > ceo /// 테이블 기본 추가 - 미완성
> feat: noticedetail > ceo /// 테이블 기본 추가 - 미완성

- src/widgets/mypage/ui/ApplicationContent/ApplicationContent.tsx
> fix: mypage /// 페이지네이션 offset, limit 변경
> fix: mypage /// 페이지네이션 offset, limit 변경

- src/models/auth/signupMutation.ts
- src/shared/utils/axios.ts
feat: 회원가입 시 중복된 이메일이면 모달 창 띄우기
> feat: 회원가입 시 중복된 이메일이면 모달 창 띄우기

- src/models/notice/noticeSubmit.ts
> fix: mystore > 등록하기 /// 에러 수정
> fix: mystore > 등록하기 /// 에러 수정

- src/shared/components/Header/Header.tsx
> feat: header logo 클릭 시 noticeList 페이지로 리다이렉트 추가

- src/components/user/ui/ApplicationDetailsEmptyList/ApplicationDetailsEmptyList.tsx
- src/models/employer/useOwnerSupportList.ts
- src/models/employer/useSetApprovalStatus.ts
- src/pages/noticedetail/index.styled.ts
- src/pages/noticedetailceo.tsx
- src/shared/components/OwnerTable/OwnerTable.styled.ts
- src/shared/components/OwnerTable/OwnerTable.tsx
- src/shared/components/OwnerTable/TableBtn/TableBtn.styled.ts
- src/shared/components/OwnerTable/TableBtn/TableBtn.tsx
- src/shared/components/Table/table.styled.ts
- src/shared/types/table.ts
> noticedetailceo > table /// 승인 거절 버튼 추가 등 기능 추가
> feat: noticedetailceo > table /// 승인 거절 버튼 추가 등 기능 추가

- src/models/auth/useSigninMutation.ts
- src/models/store/mutateAddStore.ts
- src/models/store/mutateUpdateStore.ts
> fix: statusCode에 따른 분기처리 수정

- src/models/user/useUpdateUserState.ts
- src/widgets/registrationMyPage/ui/registrationProfile/RegistrationProfile.tsx
> refactor: refactoring

- src/pages/noticelist/index.styled.ts
- src/shared/components/Post/PostCard/PostCard.styled.ts
- src/shared/components/Post/PostInform/PostInform.styled.ts
- src/shared/components/Post/PostList/PostList.styled.ts
- src/shared/components/Post/PostPrice/PostPrice.styled.ts
- src/shared/components/Post/PostPrice/PostPriceBadge.styled.ts
- src/shared/components/PostList/PostPrice/PostPrice.styled.ts
- src/widgets/noticelist/ui/SortDropdown/SortDropdown.styled.ts
> style: PostCard 스타일 수정

- src/models/dropdown/toggleDropDown.ts
- src/models/filter/handleApplyFilters.ts
- src/models/modal/toggleFilterModal.ts
- src/models/sort/handleSortOptionClick.ts
- src/pages/noticelist/index.tsx
> noticelist 의 로직들을 models로 분리
> refactor: 로직 refactoring

- .bash_profile
- src/models/notice/useGetCustomNotices.ts
- src/models/notice/useGetNotices.ts
- src/models/user/useUserUpdateForm.ts
- src/pages/noticelist/index.tsx
- src/widgets/noticelist/ui/CustomPostList/CustomPostList.tsx
- src/widgets/registrationMyPage/ui/registrationProfile/RegistrationProfile.tsx
> feat: 맞춤 공고 제작

- README.md
- src/constant/path.ts
- src/shared/components/Post/PostCard/PostCard.tsx
- src/shared/components/Table/Table.tsx
> fix: 경로 에러 수정

- src/components/notifications/ui/NotificationModal/NotificationItem/NotificationItem.styled.ts
- src/components/notifications/ui/NotificationModal/NotificationModal.styled.ts
- src/components/user/ui/ApplicationDetailsEmptyList/ApplicationDetailsEmptyList.styled.ts
- src/components/user/ui/ApplicationHistoryTableContent/ApplicationHistoryTableContent.styled.ts
- src/pages/noticedetail/index.styled.ts
- src/shared/components/Header/Header.styled.ts
- src/shared/components/Header/isLogin/IsLogin.tsx
- src/shared/components/OwnerTable/OwnerTable.styled.ts
- src/shared/components/Table/table.styled.ts
- src/widgets/mypage/ui/ProfileContent/ProfileContent.styled.ts
- src/widgets/mypage/ui/ProfileContent/ProfileContent.tsx
- src/widgets/mystore/ui/NoticeContent/NoticeContent.styled.ts
- src/widgets/mystore/ui/NoticeContent/NoticeContent.tsx
> style: 스타일 추가 수정

- src/shared/utils/useRouterGuard.ts
> feat: useRouterGuard path 추가

- src/shared/utils/useRouterGuard.ts
> fix: router guard 에러 수정

- src/shared/components/Header/notLogin/notLogin.tsx
> feat: 미 로그인 시 header nav에 href 추가

- src/widgets/noticelist/index.ts
- src/widgets/noticelist/ui/CustomNotFoundPost/CustomNotFoundPost.styled.ts
- src/widgets/noticelist/ui/CustomNotFoundPost/CustomNotFoundPost.tsx
- src/widgets/noticelist/ui/CustomPostList/CustomPostList.tsx
> Feat: 맞춤 공고 없을 때

- src/shared/components/Post/PostCard/PostCard.tsx
- src/shared/components/Post/PostImage/PostImage.tsx
- src/shared/components/Post/PostList/PostList.tsx
> feat: 지난 공고일 경우 로직 추가

- src/pages/noticedetail/ceo/noticedetailceo.tsx
- src/pages/noticedetail/index.tsx
- src/shared/components/Post/PostPrice/PostPrice.tsx
- src/widgets/noticedetail/ui/ShopDetailWidget/ShopDetailWidget.tsx
fix: notice detail type error fixed
> fix: notice detail type error fixed

- src/components/notice/ui/noticeCardList/NoticeCardList.tsx
- src/components/user/ui/ViewProfile/ViewProfile.styled.ts
- src/shared/components/Button/CustomButton/CustomButton.tsx
- src/shared/components/Button/GrayButton/GrayButton.tsx
- src/shared/store/useUserData.ts
- src/widgets/mystore/ui/StoreContent/StoreContent.styled.ts
- src/widgets/noticedetail/ui/DetailWidget/DetailWidget.tsx
- src/widgets/noticelist/ui/CustomPostList/CustomPostList.tsx
> fix: build error fixed
